[package]
name = "api-doc-macros"
version = "0.1.0"
edition = "2024"


[lib]
proc-macro = true

[dependencies]
aide = { version = "0.15.1", features = ["axum-extra-query"] }
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
